version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/your_database
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
