"""init schema

Revision ID: c6329f72e465
Revises: 
Create Date: 2025-08-23 17:55:28.427775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6329f72e465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platforms', sa.String(), nullable=True),
    sa.Column('tactics', sa.Text(), nullable=True),
    sa.Column('data_sources', sa.String(), nullable=True),
    sa.Column('detection', sa.String(), nullable=True),
    sa.Column('permissions_required', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacks_id'), 'attacks', ['id'], unique=False)
    op.create_index(op.f('ix_attacks_technique_id'), 'attacks', ['technique_id'], unique=True)
    op.create_table('capecs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capec_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('likelihood_of_attack', sa.String(), nullable=True),
    sa.Column('typical_severity', sa.String(), nullable=True),
    sa.Column('related_weaknesses', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('mitigations', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('example_instances', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capecs_capec_id'), 'capecs', ['capec_id'], unique=True)
    op.create_index(op.f('ix_capecs_id'), 'capecs', ['id'], unique=False)
    op.create_table('cves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('exploitability', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cves_cve_id'), 'cves', ['cve_id'], unique=True)
    op.create_index(op.f('ix_cves_id'), 'cves', ['id'], unique=False)
    op.create_table('cwes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('common_consequenses', sa.Text(), nullable=True),
    sa.Column('potential_mitigations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cwes_cwe_id'), 'cwes', ['cwe_id'], unique=True)
    op.create_index(op.f('ix_cwes_id'), 'cwes', ['id'], unique=False)
    op.create_table('asset_cve_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['cve_id'], ['cves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_cve_relations_id'), 'asset_cve_relations', ['id'], unique=False)
    op.create_table('capec_attack_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capec_id', sa.Integer(), nullable=False),
    sa.Column('attack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ),
    sa.ForeignKeyConstraint(['capec_id'], ['capecs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capec_attack_relations_id'), 'capec_attack_relations', ['id'], unique=False)
    op.create_table('cve_cwe_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cve_id'], ['cves.id'], ),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cve_cwe_relations_id'), 'cve_cwe_relations', ['id'], unique=False)
    op.create_table('cwe_capec_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False),
    sa.Column('capec_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capec_id'], ['capecs.id'], ),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cwe_capec_relations_id'), 'cwe_capec_relations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cwe_capec_relations_id'), table_name='cwe_capec_relations')
    op.drop_table('cwe_capec_relations')
    op.drop_index(op.f('ix_cve_cwe_relations_id'), table_name='cve_cwe_relations')
    op.drop_table('cve_cwe_relations')
    op.drop_index(op.f('ix_capec_attack_relations_id'), table_name='capec_attack_relations')
    op.drop_table('capec_attack_relations')
    op.drop_index(op.f('ix_asset_cve_relations_id'), table_name='asset_cve_relations')
    op.drop_table('asset_cve_relations')
    op.drop_index(op.f('ix_cwes_id'), table_name='cwes')
    op.drop_index(op.f('ix_cwes_cwe_id'), table_name='cwes')
    op.drop_table('cwes')
    op.drop_index(op.f('ix_cves_id'), table_name='cves')
    op.drop_index(op.f('ix_cves_cve_id'), table_name='cves')
    op.drop_table('cves')
    op.drop_index(op.f('ix_capecs_id'), table_name='capecs')
    op.drop_index(op.f('ix_capecs_capec_id'), table_name='capecs')
    op.drop_table('capecs')
    op.drop_index(op.f('ix_attacks_technique_id'), table_name='attacks')
    op.drop_index(op.f('ix_attacks_id'), table_name='attacks')
    op.drop_table('attacks')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
